Algoritmo "area do losango"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gyovanna Silva
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
   diagonalMaior: real
   diagonalMenor: real
   resultado: real
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreva ("digite o valor do diagonal maior do losango")
      leia (diagonalMaior)
      escreva("digite o valor do diagonal menor do losango")
      leia(diagonalMenor)
      resultado<- (diagonalMaior * diagonalMenor/2)
      escreva("o resultado da area do losango é:", resultado)
      

Fimalgoritmo