Algoritmo "Area"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jialson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gygy
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
   raio:real
   areacirculo: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("digite o valor do raio para calcular  a area do circulo")
   leia(raio)
   areacirculo <-3.14 * raio^2
   escreva("o valor da area circulo calculada é : ", areacirculo)

Fimalgoritmo