Algoritmo "quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gyovanna Silva
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis
lado:real
resuktado:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite o valor do lado do quadrado")
 leia(lado)
 resultado<- (lado * lado)
 escreva ("o valor da area do quadrado é:" ,resultado, "cm")

Fimalgoritmo