Algoritmo "SejaBemvindo2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   :Seja Bem-Vinda Gavião da Fiel
// Autor(a)    : Gyovanna Silva Gonçalves
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
nome:caractere
sobrenome: caractere
nomecompleto: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite seu nome: ")
leia(nome)
escreva("digite seu sobrenome: ")
leia(sobrenome)
nomecompleto<-nome + " " + sobrenome
escreva("seja bem vindo gavioes da Fiel ", nomecompleto)


Fimalgoritmo