Algoritmo "+1-1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gyovanna
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
numero1:real
antecessor: real
Numero2:real
sucessor: real
resultado: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite primeiro numero")
leia(numero1)
escreva("digite segundo numero")
leia(numero2)
resultado<-numero1-2

resultado<-numero2+1
escreva ("o resultado dos numeros é:", resultado)
Fimalgoritmo